apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: aihe-framework-staging
data:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ALLOWED_HOSTS: "localhost,127.0.0.1"
  CORS_ORIGINS: "http://localhost:3000,http://localhost:8080"
  LOG_LEVEL: "INFO"
  ENABLE_DOCS: "true"
  ENABLE_METRICS: "true"
  ENVIRONMENT: "staging"
  DEBUG: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: aihe-framework-staging
type: Opaque
data:
  SECRET_KEY: dGVzdC1zZWNyZXQta2V5LXN0YWdpbmc=
  DB_HOST: cG9zdGdyZXM=
  DB_PORT: NTQzMg==
  DB_NAME: YWloZV9mcmFtZXdvcms=
  DB_USER: YWloZV91c2Vy
  DB_PASSWORD: YWloZV9wYXNzd29yZA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: aihe-framework-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:15
        command:
          - sh
          - -c
          - |
            until pg_isready -h postgres -p 5432; do echo waiting for postgres; sleep 2; done;
      - name: run-migrations
        image: ghcr.io/aigambitkg/aihe-meta-framework/backend:latest
        command:
          - alembic
          - upgrade
          - head
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
      containers:
      - name: backend
        image: ghcr.io/aigambitkg/aihe-meta-framework/backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        env:
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: aihe-framework-staging
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
