apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: aihe-framework
data:
  DATABASE_URL: "postgresql://aihe_user:aihe_password@postgres:5432/aihe_framework"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ALLOWED_HOSTS: "localhost,127.0.0.1"
  CORS_ORIGINS: "http://localhost:3000,http://frontend:3000"
  LOG_LEVEL: "INFO"
  ENABLE_DOCS: "true"
  ENABLE_METRICS: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: aihe-framework
type: Opaque
data:
  SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQta2V5LWhlcmU= # base64 encoded

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: aihe-framework
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:15
        command: ['sh', '-c', 'until pg_isready -h postgres -p 5432; do echo waiting for postgres; sleep 2; done;']
      - name: run-migrations
        image: aihe-backend:latest
        command: ['alembic', 'upgrade', 'head']
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
      containers:
      - name: backend
        image: aihe-backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: aihe-framework
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: aihe-framework
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
